name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Go version
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Test build
        run: make
